### ISSUE TITLE
Suggestion/question about colors 

### ISSUE THREAD

**Issue by oknozor** [francma/wob#45]
Hey it took me some times to figure out how to use colors and I am still not sure about the meaning of the first two hex value (#**FF**000000). Is this opacity ? 

I think you should really provide some examples and documentation in the readme and manpage.

**Comment by francma** [comment]
Yes, first 2 hex letters represent opacity. Unfortunately it was bugged before version 0.9  #39

**Comment by oknozor** [comment]
Thank you, I might submit a PR to improve the doc next week, i have no time to do it right now.

**Comment by PaperMountainStudio** [comment]
@oknozor when you will be updating the documentation, could you add the section "General usage" from README.md to the manpage? When someone installs wob from repositories, they have to look up the Github repository (or be experienced linux users), because manpages don't give too much information about how to use it properly.
