### ISSUE TITLE
Change color format from #argb to #rgba

### ISSUE THREAD

**Issue by francma** [francma/wob#70]
Most RGB with alpha color representations are in #RRGGBBAA format - for example

- https://codeberg.org/dnkl/foot/
- swaybg

**Comment by Brod8362** [comment]
Additional idea - maybe make the alpha optional? Just default to fully opaque if not specified.

**Comment by RicArch97** [comment]
Changing the colours to "#RRGGBB" and "#RRGGBBAA" would be a very welcome change. Would make it easier to pass along colors generated by PyWal for example.

**Comment by 532910** [comment]
I believe the color format should be <RRGGBB[AA]> instead of the current <#AARRGGBB>. The same as in swaynag for example

**Comment by FallenChromium** [comment]
Absolutely agree, if the RGB color is used as a variable, it will be possible to just add the opacity afterwards, and you can't do that (easily) with argb format, because there will be 2 `#` symbols. Though if anyone would share their solution to this problem it will be appreciated. I gave up trying to use my sway RGB variables as colors for wob because of that format mess.
